# Generated by Django 4.2.1 on 2023-06-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feeding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeding',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='finch',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
